name: Build and push
on:
  push:
    tags:
      - '*'

jobs:
  work:
    name: Work
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build & Push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tag_with_ref: true
          registry: ghcr.io
          repository: democraciaenred/red-de-innovacion-politica
